name = "JCD"
license = "MIT"
description = "Jazzclub Darmstadt' modification of the vimux blank theme"
homepage = "https://github.com/vimux/blank/"

[author]
  name = "Jazzclub Darmstadt"
  homepage = "https://github.com/qwerbzuio/jcd"
